### ISSUE TITLE
More than 2 return values do not get parsed correctly

### ISSUE THREAD

**Issue by Aurora12** [reflog/struct2interface#1]
struct2interface is used by the current version of [mattermost-server](https://github.com/mattermost/mattermost-server/), this is how I've found out.

They have a method 
```
func (a *App) GetSchemeRolesForChannel(channelId string) (guestRoleName, userRoleName, adminRoleName string, err *model.AppError) {
```
that gets interfaced as 
```
GetSchemeRolesForChannel(channelId string) (string, *model.AppError)
```

The bug has to be on the [line 51 of main.go](https://github.com/reflog/struct2interface/blob/master/main.go#L51).

Unless I'm much mistaken, that's because `len(fun.Type.Results.List)` is 2, but  `fun.Type.Results.NumFields()` is 4 when it gets to `GetSchemeRolesForChannel`, but I'm not very experienced with Go. 

Steps to reproduce:

1.  pull [mattermost-server](https://github.com/mattermost/mattermost-server/)
2. edit /Makefile to uncomment the lines in `app-layers` task
3. `make app-layers`
4. see `GetSchemeRolesForChannel` on line 650 of `mattermost-server/app/channel.go`
5. compare to `GetSchemeRolesForChannel` generated to `mattermost-server/app/app_iface.go`

**Comment by Aurora12** [comment]
The code generated from this declaration is correct:
`func (a *App) GetSchemeRolesForChannel(channelId string) (guestRoleName string, userRoleName string, adminRoleName string, err *model.AppError) {`

Output:
`GetSchemeRolesForChannel(channelId string) (string, string, string, *model.AppError)`

The code with two first types skipped generates a wrong signature:
`func (a *App) GetSchemeRolesForChannel(channelId string) (guestRoleName, userRoleName, adminRoleName string, err *model.AppError) {`

Output:
`GetSchemeRolesForChannel(channelId string) (string, *model.AppError)`

**Comment by reflog** [comment]
@Aurora12 thanks for the report! Fixed and new version is released.
